### ISSUE TITLE
Nicklist desyncing

### ISSUE THREAD

**Issue by wowaname** [wowaname/OG-IRCd#8]
Nicklist sometimes desyncs and has more (already parted) users than there currently are in the channel. A /NAMES request does not fix it; only a rejoin does. The question is, what is causing ngircd to think that these people are still in the channel and why is it fixable on a per-user basis? The channel's nicklist should be consistent across all members of that channel.

I am not using usermode +d (deaf -- known to be buggy but still exists as a mode so that I can one day try to fix it) so this should not be causing it. Either way, if it was umode +d then the /NAMES list would not be affected.

It would be appreciated if someone can do some in-depth analysis on the issue and reproduce it reliably, if I don't get to it first.

**Comment by j4jackj** [comment]
PARTs are not being sent by the server to the user.

**Comment by wowaname** [comment]
That helps a little but I don't think it explains why /names doesn't update. Maybe the servers aren't synced? Even then that sounds improbable...

**Comment by j4jackj** [comment]
Well, I just tried something on Volatile, and no QUIT was sent to me for ukkie, the test client.

**Comment by wowaname** [comment]
It has to do with the +u mode.

**Comment by wowaname** [comment]
Should be fixed. If anyone sees this behaviour again I'll reopen.
